/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gds_jniutils_JniUtils */

#ifndef _Included_com_gds_jniutils_JniUtils
#define _Included_com_gds_jniutils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gds_jniutils_JniUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gds_jniutils_JniUtils_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_gds_jniutils_JniUtils
 * Method:    updateFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gds_jniutils_JniUtils_updateFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
